#############################################################################
# Makefile for building: ARProject
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  ARProject.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile ARProject.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Iinclude -I/usr/include/qt5 -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/X11R6/lib -L/usr/local/lib -L/media/marcct/e75084af-4dd9-43d5-b82f-3cf5d497678f/Dropbox/MIRI/VAR/ARProject/lib -lARgsub -lARvideo -lAR -lglut -lGLU -lXi -lX11 -lm -pthread -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0 -lGLEW -lassimp -lQt5Gui -L/usr/lib/x86_64-linux-gnu -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mesh.cpp \
		renderableobject.cpp \
		bbox.cpp \
		pattern.cpp \
		animatedobject.cpp \
		turret.cpp 
OBJECTS       = main.o \
		mesh.o \
		renderableobject.o \
		bbox.o \
		pattern.o \
		animatedobject.o \
		turret.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ARProject.pro \
		ARProject.pro
QMAKE_TARGET  = ARProject
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ARProject


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	mkdir -p Data & cp -f /media/marcct/e75084af-4dd9-43d5-b82f-3cf5d497678f/Dropbox/MIRI/VAR/ARProject/Data/* Data &

Makefile: ARProject.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ARProject.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 -o Makefile ARProject.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ARProject.pro:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile ARProject.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/ARProject1.0.0 || mkdir -p .tmp/ARProject1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ARProject1.0.0/ && $(COPY_FILE) --parents mesh.h renderableobject.h bbox.h pattern.hpp animatedobject.h turret.h .tmp/ARProject1.0.0/ && $(COPY_FILE) --parents main.cpp mesh.cpp renderableobject.cpp bbox.cpp pattern.cpp animatedobject.cpp turret.cpp .tmp/ARProject1.0.0/ && (cd `dirname .tmp/ARProject1.0.0` && $(TAR) ARProject1.0.0.tar ARProject1.0.0 && $(COMPRESS) ARProject1.0.0.tar) && $(MOVE) `dirname .tmp/ARProject1.0.0`/ARProject1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ARProject1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp include/AR/gsub.h \
		include/AR/config.h \
		include/AR/param.h \
		include/AR/ar.h \
		include/AR/video.h \
		include/AR/sys/videoWin32DirectShow.h \
		include/AR/sys/videoLinuxV4L.h \
		include/AR/sys/videoLinuxDV.h \
		include/AR/sys/videoLinux1394Cam.h \
		include/AR/sys/videoGStreamer.h \
		include/AR/sys/videoSGI.h \
		include/AR/sys/videoMacOSX.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		pattern.hpp \
		mesh.h \
		renderableobject.h \
		bbox.h \
		animatedobject.h \
		turret.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mesh.o: mesh.cpp mesh.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		renderableobject.h \
		bbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesh.o mesh.cpp

renderableobject.o: renderableobject.cpp renderableobject.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderableobject.o renderableobject.cpp

bbox.o: bbox.cpp bbox.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bbox.o bbox.cpp

pattern.o: pattern.cpp pattern.hpp \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		include/AR/gsub.h \
		include/AR/config.h \
		include/AR/param.h \
		include/AR/ar.h \
		include/AR/video.h \
		include/AR/sys/videoWin32DirectShow.h \
		include/AR/sys/videoLinuxV4L.h \
		include/AR/sys/videoLinuxDV.h \
		include/AR/sys/videoLinux1394Cam.h \
		include/AR/sys/videoGStreamer.h \
		include/AR/sys/videoSGI.h \
		include/AR/sys/videoMacOSX.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pattern.o pattern.cpp

animatedobject.o: animatedobject.cpp animatedobject.h \
		mesh.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		renderableobject.h \
		bbox.h \
		pattern.hpp \
		include/AR/gsub.h \
		include/AR/config.h \
		include/AR/param.h \
		include/AR/ar.h \
		include/AR/video.h \
		include/AR/sys/videoWin32DirectShow.h \
		include/AR/sys/videoLinuxV4L.h \
		include/AR/sys/videoLinuxDV.h \
		include/AR/sys/videoLinux1394Cam.h \
		include/AR/sys/videoGStreamer.h \
		include/AR/sys/videoSGI.h \
		include/AR/sys/videoMacOSX.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animatedobject.o animatedobject.cpp

turret.o: turret.cpp turret.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o turret.o turret.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

